### ISSUE TITLE
resadapter-v1.5生成1024的代码

### ISSUE THREAD

**Issue by liushanyuan18** [bytedance/res-adapter#10]
感谢杰出的工作！
请问可以提供一下resadapter-v1.5生成1024的代码吗，readme中的代码只用到了resolution_lora.safetensors，没有用到resolution_normalization.safetensors，无法生成合理的1024图片

**Comment by jiaxiangc** [comment]
感谢支持和提醒，我今晚会上传sd1.5版本的1024载入代码。
我们马上会支持resadapter的webui和comfyui，多谢支持哈。

**Comment by jiaxiangc** [comment]
@liushanyuan18 
你好，我们更新了加载sd1.5，resolution_normalization的代码，你可以使用它配合个性化扩散模型生成1024的图像。
地址：https://github.com/bytedance/res-adapter/blob/main/resadapter/model_loader.py
⚠️需要注意的点：
- 对于Text to images的任务，尽可能使用个性化模型，而不要使用base model。虽然我们的Resadapter是基于base model训练的，但是我们释放的权重是面向个性化模型的。
- 对于其他任务，如ControlNet、IP-Adapter，可以使用base model作为基础模型。

**Comment by liushanyuan18** [comment]
感谢！
