### ISSUE TITLE
ValueError: PEFT backend is required for `set_adapters()`.

### ISSUE THREAD

**Issue by fly2outerspace** [bytedance/res-adapter#18]
Running with given fast code, the only change is "model_name = "Lykon/dreamshaper-xl-1-0" "
here are my codes:( basicly yours)

import torch
from torchvision.utils import save_image
from safetensors.torch import load_file
from huggingface_hub import hf_hub_download
from diffusers import AutoPipelineForText2Image, DPMSolverMultistepScheduler

generator = torch.manual_seed(0)
prompt = "portrait photo of muscular bearded guy in a worn mech suit, light bokeh, intricate, steel metal, elegant, sharp focus, soft lighting, vibrant colors"
width, height = 640, 384

# Load baseline pipe
model_name = "Lykon/dreamshaper-xl-1-0"
pipe = AutoPipelineForText2Image.from_pretrained(model_name, torch_dtype=torch.float16, variant="fp16").to("cuda")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True, algorithm_type="sde-dpmsolver++")

# Inference baseline pipe
image = pipe(prompt, width=width, height=height, num_inference_steps=25, num_images_per_prompt=4, output_type="pt").images
save_image(image, f"image_baseline.png", normalize=True, padding=0)

# Load resadapter for baseline
resadapter_model_name = "resadapter_v1_sdxl"
pipe.load_lora_weights(
    hf_hub_download(repo_id="jiaxiangc/res-adapter", subfolder=resadapter_model_name, filename="pytorch_lora_weights.safetensors"), 
    adapter_name="res_adapter",
    ) # load lora weights
pipe.set_adapters(["res_adapter"], adapter_weights=[1.0])
pipe.unet.load_state_dict(
    load_file(hf_hub_download(repo_id="jiaxiangc/res-adapter", subfolder=resadapter_model_name, filename="diffusion_pytorch_model.safetensors")),
    strict=False,
    ) # load norm weights

# Inference resadapter pipe
image = pipe(prompt, width=width, height=height, num_inference_steps=25, num_images_per_prompt=4, output_type="pt").images
save_image(image, f"image_resadapter.png", normalize=True, padding=0)

error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 27
     22 resadapter_model_name = "resadapter_v1_sdxl"
     23 pipe.load_lora_weights(
     24     hf_hub_download(repo_id="jiaxiangc/res-adapter", subfolder=resadapter_model_name, filename="pytorch_lora_weights.safetensors"), 
     25     adapter_name="res_adapter",
     26     ) # load lora weights
---> 27 pipe.set_adapters(["res_adapter"], adapter_weights=[1.0])
     28 pipe.unet.load_state_dict(
     29     load_file(hf_hub_download(repo_id="jiaxiangc/res-adapter", subfolder=resadapter_model_name, filename="diffusion_pytorch_model.safetensors")),
     30     strict=False,
     31     ) # load norm weights
     33 # Inference resadapter pipe

File /usr/local/lib/python3.10/dist-packages/diffusers/loaders/lora.py:1248, in LoraLoaderMixin.set_adapters(self, adapter_names, adapter_weights)
   1246 unet = getattr(self, self.unet_name) if not hasattr(self, "unet") else self.unet
   1247 # Handle the UNET
-> 1248 unet.set_adapters(adapter_names, adapter_weights)
   1250 # Handle the Text Encoder
   1251 if hasattr(self, "text_encoder"):

File /usr/local/lib/python3.10/dist-packages/diffusers/loaders/unet.py:599, in UNet2DConditionLoadersMixin.set_adapters(self, adapter_names, weights)
    572 """
    573 Set the currently active adapters for use in the UNet.
    574 
   (...)
    596 ```
    597 """
    598 if not USE_PEFT_BACKEND:
--> 599     raise ValueError("PEFT backend is required for `set_adapters()`.")
    601 adapter_names = [adapter_names] if isinstance(adapter_names, str) else adapter_names
    603 if weights is None:

ValueError: PEFT backend is required for `set_adapters()`.

how to solve this?

**Comment by jiaxiangc** [comment]
What version is your PEFT？ Try to update PEFT version to latest.

**Comment by fly2outerspace** [comment]
Thank you! I solved it by install peft, maybe you guys need to add it to the comments. Thanks for your great work!
