### ISSUE TITLE
你好，我安装了ComfyUI-ResAdapter，但在ComfyUI里找不到这个节点。

### ISSUE THREAD

**Issue by zoenders** [bytedance/res-adapter#23]
你好，我安装了ComfyUI-ResAdapter，依赖也已经装好了，但在ComfyUI里找不到这个节点。搜索ResAdapter也没有。请问是什么问题？

**Comment by jiaxiangc** [comment]
你看一下ComfyUI-ResAdapter前面是否出现 ImportFailed，在终端看。

**Comment by zoenders** [comment]
> 你看一下ComfyUI-ResAdapter前面是否出现 ImportFailed，在终端看。

对，是(IMPORT FAILED) [ResAdapter for ComfyUI](https://github.com/jiaxiangc/ComfyUI-ResAdapter)
