### ISSUE TITLE
Over 1024px?

### ISSUE THREAD

**Issue by andupotorac** [bytedance/res-adapter#24]
Hi. We're currently testing the LORA, but as soon as we apply it on images over 1024px, it doesn't work anymore for SD 1.5. Why is there a limit?

**Comment by jiaxiangc** [comment]
We suggests you use resadapter with personalized models, SD1.5's ability is normal.
And resadapter-sdv15 only support less than 1024px.

**Comment by andupotorac** [comment]
Thanks for your reply. I did use resadapter with a personalised checkpoint (ICBINP) and this was still the result. Or you mean something else?

**Comment by jiaxiangc** [comment]
What is your resolution? if the resolution more than 1024px, the results are not good.

**Comment by andupotorac** [comment]
> What is your resolution? if the resolution more than 1024px, the results are not good.

Yes I figured. When it goes above 1024 it's problematic. I guess regional prompting could fix this.

**Comment by jiaxiangc** [comment]
> > What is your resolution? if the resolution more than 1024px, the results are not good.
> 
> Yes I figured. When it goes above 1024 it's problematic. I guess regional prompting could fix this.

yes, maybe train-free methods can fix this.
