### ISSUE TITLE
Just add Lora and I can increase or decrease the resolution ?

### ISSUE THREAD

**Issue by madeirafranciscoluxio** [bytedance/res-adapter#9]
Do I need to add both loras?

I tested one of the loras and I can create images with SDXL with resolution 512 and 256. I think it works. Without Lora the images look much worse at 256 X 256 resolution. But at resolution 512 the difference doesn't seem so significant

But when trying resolutions higher than 1024 the images have duplicated, distorted people

**Comment by jiaxiangc** [comment]
@madeirafranciscoluxio Thanks for your attention.
For SDXL, just load sdxl-i/resolution_lora.safetensors to generate images (256~1024). So it can not support resolution higher than 1024 temporally. But we will release models to support higher resolution.

If you find resolution at 512 the difference dosen't seem so significant. You can change your sample scheduler (such as, DDIM, DPM Solver, etc.). In serval schedulers, resadapter can not be activated.

**Comment by jiaxiangc** [comment]
can you provide detailed codes for me?

**Comment by jiaxiangc** [comment]
We provide an [example](https://github.com/bytedance/res-adapter#-standalone-example-with-sdxl-lighting) about SDXL-Lightning.
